-- =========================================================================
-- Purpose of this file:
-- This SQL script defines the database schema for the Electrical Contractor CRM.
-- It creates three key tables: users (holding both admins and clients), projects, 
-- and documents. By using SQLite constraints like foreign keys and CHECK clauses,
-- it ensures data integrity at the database layer.
--
-- How requests flow & interact with these tables:
-- 1. When a user logs in (Admin or Client), the backend queries the 'users' table.
-- 2. When an Admin manages clients, they write/read from the 'users' table where role = 'client'.
-- 3. When projects are created/updated/assigned, they write to the 'projects' table, referencing a client ID from the 'users' table.
-- 4. When files are uploaded, they are stored on disk, and a record is created in the 'documents' table linking them to a specific project.
-- =========================================================================

-- Enable foreign key constraints in SQLite (must be run per database connection)
PRAGMA foreign_keys = ON;

-- 1. Users Table
-- This table stores credentials and details for both Admin and Client users.
-- Storing both in a single table with a 'role' column simplifies query login
-- and ensures unique email constraints across the entire application.
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, -- Hashed using bcryptjs
    role TEXT NOT NULL CHECK(role IN ('admin', 'client')),
    company TEXT, -- Relevant only for clients (e.g., 'DHBVN', 'City Grid')
    phone TEXT,   -- Contact number
    address TEXT, -- Physical or billing address
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Projects Table
-- This table tracks the electrical contracting projects (e.g. Substation Commissioning).
-- It contains a foreign key 'clientId' linking the project to a client in the 'users' table.
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    clientId INTEGER,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'in_progress', 'completed', 'cancelled')),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(clientId) REFERENCES users(id) ON DELETE SET NULL
);

-- 3. Documents Table
-- This table tracks files uploaded for projects (blueprints, inspector certificates, contracts).
-- Instead of storing binary data in SQLite (which slows down database operations), we store 
-- the files in the 'uploads/' folder and reference their file paths in this table.
CREATE TABLE IF NOT EXISTS documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    projectId INTEGER NOT NULL,
    name TEXT NOT NULL,       -- Original file name (e.g., 'substation_wiring.pdf')
    filename TEXT NOT NULL,   -- Unique disk name generated by Multer (e.g., '168393939-substation_wiring.pdf')
    filepath TEXT NOT NULL,   -- Path to locate the file in the file system
    uploadedBy INTEGER,       -- The user ID of the admin who uploaded it
    uploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY(uploadedBy) REFERENCES users(id) ON DELETE SET NULL
);
